# Cấu hình chính cho VNEconomy

# ============ SePay Config ============
sepay:
  bank: "MBBank"
  account_number: "0280110919999"
  template: "compact"
  prefix: "NapTien"
  webhook:
    enabled: true
    port: 8080
    secret: "" # tuỳ chọn, nếu bạn bật xác thực chữ ký webhook ở SePay thì lưu secret ở đây

order_expire_ms: 60000

webhook:
  enabled: true
  url: "YOUR_DISCORD_WEBHOOK_URL"

currency:
  symbol: "₫"
  # hiển thị dạng VND, ví dụ 1000000 -> 1,000,000 ₫
  suffix: " ₫"
  use-short-format: true       # nếu true: 1.2M ₫, 950K ₫
  decimals: 0                  # số lẻ

storage:
  #sqlite | mysql
  type: "sqlite"

mysql:
  host: "localhost"
  port: 3306
  database: "vneconomy"
  username: "root"
  password: "password"
  useSSL: false
  pool:
    maximumPoolSize: 10
    minimumIdle: 2

sqlite:
  file: "economy.db"

leaderboard:
  cache-seconds: 60
  size: 10

# ==============================
# ⚡ VNEconomy - TheSieuToc Config
# ==============================

# API TheSieuToc
TheSieuToc-API:
  key: "API_KEY_CUA_BAN"
  prices:
    10000: 10000
    20000: 20000
    50000: 50000
    100000: 100000

thesieutoc:
  webhook:
    enabled: true
    port: 8080
    path: "/callback"

# ==============================
# ⚡ Cài đặt khác
# ==============================

# Tỉ lệ quy đổi tiền nạp thành xu trong game
# Ví dụ: 10000 VND = 100 xu
exchange-rate: 0.01


Supported-Cards:
  - VIETTEL
  - MOBIFONE
  - VINAPHONE
  - ZING
  - GATE

messages:
  prefix: "&e&lVNECO &7» "
  no-permission: "&cBạn không có quyền!"
  player-not-found: "&cKhông tìm thấy người chơi &e%player%&c."
  invalid-number: "&cSố tiền không hợp lệ."
  negative-amount: "&cSố tiền phải lớn hơn 0."
  self-pay: "&cBạn không thể chuyển tiền cho chính mình."
  balance-self: "&aSố dư của bạn: &e%amount%"
  balance-other: "&aSố dư của &e%player%&a: &e%amount%"
  paid-sender: "&aĐã chuyển &e%amount%&a cho &e%target%&a."
  paid-receiver: "&aBạn nhận được &e%amount%&a từ &e%sender%&a."
  top-header: "&6&lTOP %size% NGƯỜI GIÀU NHẤT:"
  top-line: "&e%pos%. &f%player% &7- &a%amount%"
  set: "&aĐã đặt tiền của &e%player%&a thành &e%amount%."
  give: "&aĐã cộng &e%amount%&a cho &e%player%."
  take: "&aĐã trừ &e%amount%&a của &e%player%."
  reloaded: "&aĐã reload cấu hình và dữ liệu."
  sound-muted: "&7Âm thanh đã tắt cho bạn."
  sound-unmuted: "&aÂm thanh đã bật cho bạn."

sounds:
  enabled-by-default: true
  success: "ENTITY_EXPERIENCE_ORB_PICKUP"
  error: "BLOCK_ANVIL_LAND"
  pay: "ENTITY_ITEM_PICKUP"
  top: "UI_TOAST_CHALLENGE_COMPLETE"
